widgets:
    type: rest
    prefix: /v1
    resource: Regidium\WidgetBundle\Controller\WidgetController
    name_prefix:  api_1_

widget_plan:
    type:     rest
    parent:   widgets
    resource: Regidium\WidgetBundle\Controller\WidgetPlanController

widget_agent:
    type:     rest
    parent:   widgets
    resource: Regidium\WidgetBundle\Controller\WidgetAgentController

widget_chat:
    type:     rest
    parent:   widgets
    resource: Regidium\WidgetBundle\Controller\WidgetChatController

widget_settings:
    type:     rest
    parent:   widgets
    resource: Regidium\WidgetBundle\Controller\WidgetSettingsController

widget_trigger:
    type:     rest
    parent:   widgets
    resource: Regidium\WidgetBundle\Controller\WidgetTriggerController

widget_transaction:
    type:     rest
    parent:   widgets
    resource: Regidium\WidgetBundle\Controller\WidgetTransactionController