imports:
    - { resource: forms.yml }

parameters:
    regidium.user.handler.class: Regidium\UserBundle\Handler\UserHandler
    regidium.user.document.class: Regidium\CommonBundle\Document\User

services:
    regidium.user.handler:
        class: %regidium.user.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.user.document.class% ]