parameters:
    # Documents
    regidium.agent.document.class: Regidium\CommonBundle\Document\Agent
    regidium.auth.document.class: Regidium\CommonBundle\Document\Auth
    regidium.client.document.class: Regidium\CommonBundle\Document\Client
    regidium.billing.plan.document.class: Regidium\CommonBundle\Document\Plan
    regidium.billing.payment.document.class: Regidium\CommonBundle\Document\Payment
    regidium.billing.payment_method.document.class: Regidium\CommonBundle\Document\PaymentMethod
    regidium.chat.document.class: Regidium\CommonBundle\Document\Chat
    regidium.chat.message.document.class: Regidium\CommonBundle\Document\ChatMessage
    regidium.client.document.class: Regidium\CommonBundle\Document\Client
    regidium.user.document.class: Regidium\CommonBundle\Document\User
    regidium.file.document.class: Regidium\CommonBundle\Document\File
    regidium.person.document.class: Regidium\CommonBundle\Document\Person

    # Repositories
    regidium.agent.repository.class: Regidium\CommonBundle\Repository\AgentRepository
    regidium.auth.repository.class: Regidium\CommonBundle\Repository\AuthRepository
    regidium.client.repository.class: Regidium\CommonBundle\Repository\ClientRepository
    regidium.billing.plan.repository.class: Regidium\CommonBundle\Repository\PlanRepository
    regidium.billing.payment.repository.class: Regidium\CommonBundle\Repository\PaymentRepository
    regidium.billing.payment_method.repository.class: Regidium\CommonBundle\Repository\PaymentMethodRepository
    regidium.chat.repository.class: Regidium\CommonBundle\Repository\ChatRepository
    regidium.chat.message.repository.class: Regidium\CommonBundle\Repository\ChatMessageRepository
    regidium.client.repository.class: Regidium\CommonBundle\Repository\ClientRepository
    regidium.user.repository.class: Regidium\CommonBundle\Repository\UserRepository
    regidium.file.repository.class: Regidium\CommonBundle\Repository\FileRepository
    regidium.person.repository.class: Regidium\CommonBundle\Repository\PersonRepository

services:
    regidium.agent.repository:
        class: %regidium.agent.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.agent.document.class% ]

    regidium.auth.repository:
        class: %regidium.auth.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.auth.document.class% ]

    regidium.client.repository:
        class: %regidium.client.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.client.document.class% ]

    regidium.billing.plan.repository:
        class: %regidium.billing.plan.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.billing.plan.document.class% ]

    regidium.billing.payment.repository:
        class: %regidium.billing.payment.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.billing.payment.document.class% ]

    regidium.billing.payment_method.repository:
        class: %regidium.billing.payment_method.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.billing.payment_method.document.class% ]

    regidium.chat.repository:
        class: %regidium.chat.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.chat.document.class% ]

    regidium.chat.message.repository:
        class: %regidium.chat.message.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.chat.message.document.class% ]

    regidium.client.repository:
        class: %regidium.client.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.client.document.class% ]

    regidium.file.repository:
        class: %regidium.file.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.file.document.class% ]

    regidium.user.repository:
        class: %regidium.user.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.user.document.class% ]

    regidium.person.repository:
        class: %regidium.person.repository.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.person.document.class% ]