parameters:
    validator.unique_document.class: Regidium\CommonBundle\Validator\Constraints\UniqueDocument\UniqueDocumentValidator
    validator.exist_document.class: Regidium\CommonBundle\Validator\Constraints\ExistDocument\ExistDocumentValidator

services:

    validator.unique.unique_document:
        class: %validator.unique_document.class%
        arguments: [ "@service_container" ]
        tags:
            - { name: validator.constraint_validator, alias: unique_document }

    validator.unique.exist_document:
        class: %validator.exist_document.class%
        arguments: [ "@service_container" ]
        tags:
            - { name: validator.constraint_validator, alias: exist_document }