plans:
    type: rest
    prefix: /v1
    resource: Regidium\BillingBundle\Controller\PlanController
    name_prefix:  api_1_

payments:
    type: rest
    prefix: /v1
    resource: Regidium\BillingBundle\Controller\PaymentController
    name_prefix:  api_1_