plans:
    type: rest
    prefix: /v1
    resource: Regidium\BillingBundle\Controller\PlanController
    name_prefix:  api_1_

paymentmethods:
    type: rest
    prefix: /v1
    resource: Regidium\BillingBundle\Controller\PaymentMethodController
    name_prefix:  api_1_