parameters:
    regidium.billing.plan.handler.class: Regidium\BillingBundle\Handler\PlanHandler
    regidium.billing.payment.handler.class: Regidium\BillingBundle\Handler\PaymentHandler
    regidium.billing.payment_method.handler.class: Regidium\BillingBundle\Handler\PaymentMethodHandler

    regidium.billing.plan.document.class: Regidium\CommonBundle\Document\Plan
    regidium.billing.payment.document.class: Regidium\CommonBundle\Document\Payment
    regidium.billing.payment_method.document.class: Regidium\CommonBundle\Document\PaymentMethod

services:
    regidium.billing.plan.handler:
        class: %regidium.billing.plan.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.billing.plan.document.class% ]

    regidium.billing.payment_method.handler:
        class: %regidium.billing.payment_method.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.billing.payment_method.document.class% ]

    regidium.billing.payment.handler:
        class: %regidium.billing.payment.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.billing.payment.document.class% ]