parameters:
    regidium.billing.plan.handler.class: Regidium\BillingBundle\Handler\PlanHandler
    regidium.billing.transaction.handler.class: Regidium\BillingBundle\Handler\TransactionHandler

    regidium.billing.plan.document.class: Regidium\CommonBundle\Document\Plan
    regidium.billing.transaction.document.class: Regidium\CommonBundle\Document\Transaction

services:
    regidium.billing.plan.handler:
        class: %regidium.billing.plan.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.billing.plan.document.class% ]

    regidium.billing.transaction.handler:
        class: %regidium.billing.transaction.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.billing.transaction.document.class% ]