# ApiDoc
nelmio_api_doc_bundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# Regidium
regidium:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /api/doc
        permanent: true


# RegidiumAgentBundle
regidium_agent:
    type: rest
    prefix: /api
    resource: "@RegidiumAgentBundle/Resources/config/routing.yml"

# RegidiumUserBundle
regidium_user:
    type: rest
    prefix: /api
    resource: "@RegidiumUserBundle/Resources/config/routing.yml"

# RegidiumAuthBundle
regidium_auth:
    type: rest
    prefix: /api
    resource: "@RegidiumAuthBundle/Resources/config/routing.yml"