# ApiDoc
nelmio_api_doc_bundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# Regidium
regidium:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /api/doc
        permanent: true


# RegidiumAgentBundle
agents:
    type: rest
    prefix: /api
    resource: "@RegidiumAgentBundle/Resources/config/routing.yml"

# RegidiumAuthBundle
auths:
    type: rest
    prefix: /api
    resource: "@RegidiumAuthBundle/Resources/config/routing.yml"

# RegidiumWidgetBundle
widgets:
    type: rest
    prefix: /api
    resource: "@RegidiumWidgetBundle/Resources/config/routing.yml"

# RegidiumBillingBundle
billings:
    type: rest
    prefix: /api
    resource: "@RegidiumBillingBundle/Resources/config/routing.yml"

# RegidiumServiceBundle
services:
    type: rest
    prefix: /api
    resource: "@RegidiumServiceBundle/Resources/config/routing.yml"