chats:
    type: rest
    prefix: /v1
    resource: Regidium\ChatBundle\Controller\ChatController
    name_prefix:  api_1_

chats_messages:
    type: rest
    prefix: /v1
    resource: Regidium\ChatBundle\Controller\ChatMessageController
    name_prefix:  api_1_