parameters:
    regidium.chat.handler.class: Regidium\ChatBundle\Handler\ChatHandler
    regidium.chat.message.handler.class: Regidium\ChatBundle\Handler\ChatMessageHandler

    regidium.chat.document.class: Regidium\CommonBundle\Document\Chat
    regidium.chat.message.document.class: Regidium\CommonBundle\Document\ChatMessage

services:
    regidium.chat.handler:
        class: %regidium.chat.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.chat.document.class% ]

    regidium.chat.message.handler:
        class: %regidium.chat.message.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.chat.message.document.class% ]