parameters:
    regidium.chat.handler.class: Regidium\ChatBundle\Handler\ChatHandler
    regidium.chat.message.handler.class: Regidium\ChatBundle\Handler\ChatMessageHandler
    regidium.chat.document.class: Regidium\ChatBundle\Document\Chat
    regidium.chat.message.document.class: Regidium\ChatBundle\Document\ChatMessage
    regidium.chat.repository.class: Regidium\ChatBundle\Repository\ChatRepository
    regidium.chat.message.repository.class: Regidium\ChatBundle\Repository\ChatMessageRepository

services:
    regidium.chat.handler:
        class: %regidium.chat.handler.class%
        arguments: [ "@form.factory", "@doctrine_mongodb", %regidium.chat.document.class% ]

    regidium.chat.message.handler:
        class: %regidium.chat.message.handler.class%
        arguments: [ "@form.factory", "@doctrine_mongodb", %regidium.chat.message.document.class% ]

    regidium.chat.repository:
        class: %regidium.chat.handler.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.chat.document.class% ]

    regidium.chat.message.repository:
        class: %regidium.chat.message.handler.class%
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        public: true
        arguments: [ %regidium.chat.message.document.class% ]