parameters:
    regidium.file.handler.class: Regidium\FileBundle\Handler\FileHandler
    regidium.file.document.class: Regidium\CommonBundle\Document\File

services:
    regidium.file.handler:
        class: %regidium.file.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.file.document.class% ]