imports:
    - { resource: forms.yml }

parameters:
    regidium.agent.handler.class: Regidium\AgentBundle\Handler\AgentHandler
    regidium.agent.document.class: Regidium\CommonBundle\Document\Agent

services:
    regidium.agent.handler:
        class: %regidium.agent.handler.class%
        arguments: [ @form.factory, @doctrine_mongodb, %regidium.agent.document.class% ]