#auths:
#    type: rest
#    prefix: /v1
#    resource: Regidium\AuthBundle\Controller\AuthController
#    name_prefix:  api_1_

registration:
    type: rest
    prefix: /v1
    resource: Regidium\AuthBundle\Controller\RegistrationController
    name_prefix:  api_1_

login:
    type: rest
    prefix: /v1
    resource: Regidium\AuthBundle\Controller\LoginController
    name_prefix:  api_1_

logout:
    type: rest
    prefix: /v1
    resource: Regidium\AuthBundle\Controller\LogoutController
    name_prefix:  api_1_

externalservice:
    type: rest
    prefix: /v1
    resource: Regidium\AuthBundle\Controller\ExternalServiceController
    name_prefix:  api_1_