clients:
    type: rest
    prefix: /v1
    resource: Regidium\ClientBundle\Controller\ClientController
    name_prefix:  api_1_

client_pay:
    type:     rest
    parent:   clients
    resource: Regidium\ClientBundle\Controller\ClientPayController

client_plan:
    type:     rest
    parent:   clients
    resource: Regidium\ClientBundle\Controller\ClientPlanController